a1 = 20
b1 = 10.5
c1 = "20"
a2 = float(a1)
a3 = str(a1)
b2 = int(b1)
b3 = str(b1)
c2 = int(c1)
c3 = float(c1)
print("a1 = ", a1, " data type is ", type(a1))
print("a2 = ", a2, " data type is ", type(a2))
print("a3 = ", a3, " data type is ", type(a3))
print("b1 = ", b1, " data type is ", type(b1))
print("b2 = ", b2, " data type is ", type(b2))
print("b3 = ", b3, " data type is ", type(b3))
print("c1 = ", c1, " data type is ", type(c1))
print("c2 = ", c2, " data type is ", type(c2))
print("c3 = ", c3, " data type is ", type(c3))